---
- name: Update sysctl conf
  sysctl:
    name: "{{ item.key }}"
    value:  "{{ item.value }}"
    state: present
  with_items:
    # Avoid a smurf attack
    - { key: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    # Turn on protection for bad icmp error messages
    - { key: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
    # Turn on syncookies for SYN flood attack protection
    - { key: net.ipv4.tcp_syncookies, value: 1 }
    # Turn on and log spoofed, source routed, and redirect packets
    - { key: net.ipv4.conf.all.log_martians, value: 1 }
    - { key: net.ipv4.conf.default.log_martians, value: 1 }
    # No source routed packets here
    - { key: net.ipv4.conf.all.accept_source_route, value: 0 }
    - { key: net.ipv4.conf.default.accept_source_route, value: 0 }
    # Turn on reverse path filtering
    - { key: net.ipv4.conf.all.rp_filter, value: 1 }
    - { key: net.ipv4.conf.default.rp_filter, value: 1 }
    # Make sure no one can alter the routing tables
    - { key: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { key: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { key: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { key: net.ipv4.conf.default.secure_redirects, value: 0 }
    # Don't act as a router
    - { key: net.ipv4.ip_forward, value: 0 }
    - { key: net.ipv4.conf.all.send_redirects, value: 0 }
    - { key: net.ipv4.conf.default.send_redirects, value: 0 }
    # Turn on execshild
    - { key: kernel.exec-shield, value: 1 }
    - { key: kernel.randomize_va_space, value: 1 }
    - { key: vm.swappiness, value: 0 }
    # The kernel will swap only to avoid an out of memory condition
    - { key: net.core.rmem_max, value: 16777216 }
    - { key: net.core.wmem_max, value: 16777216 }
    - { key: net.core.netdev_max_backlog, value: 5000 }
    - { key: net.ipv4.tcp_window_scaling, value: 1 }
    # Increase Linux auto tuning TCP buffer limits
    - { key: net.ipv4.tcp_tw_reuse, value: 1 }
    # Setting this directive to 1 will tell the kernel to try to recycle the allocation
    - { key: net.ipv4.tcp_fin_timeout, value: 15 }
    # This will mean will mean allocations will be recycled faster.
    # Other tunings as follows
    - { key: net.core.somaxconn, value: 4096 }
    - { key: net.ipv4.tcp_max_syn_backlog, value: 20480 }
    - { key: net.ipv4.tcp_max_tw_buckets, value: 400000 }
    - { key: net.ipv4.tcp_no_metrics_save, value: 1 }
    - { key: net.ipv4.tcp_syn_retries, value: 2 }
    - { key: net.ipv4.tcp_synack_retries, value: 2 }
    - { key: vm.min_free_kbytes, value: 65536 }
...
