---

# all-settings 
- hosts: all
  become: yes
  gather_facts: yes
  connection: ssh

  roles:
    - allmachines 

# nginx webservers
- hosts: webservers
  become: yes
  gather_facts: yes
  connection: ssh

  roles:
    - nginx-webservers

# haproxy loadbalancer
- hosts: loadbalancer
  become: yes
  gather_facts: yes
  connection: ssh

  roles:
    - haproxy-loadbalancer

...
