---
- name: write rsyslog.conf
  template: src=templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf

- name: create /etc/rsyslog.d/haproxy.conf
  template: src=templates/haproxy.conf.j2 dest=/etc/rsyslog.d/haproxy.conf
  notify:
    restart rsyslog
...
