---
- name: Update sysctl conf
  sysctl:
    name: "{{ item.key }}"
    value:  "{{ item.value }}"
    state: present
  with_items:
    - { key: net.ipv4.ip_local_port_range, value: "1025 65534" }
    - { key: net.ipv4.tcp_max_syn_backlog, value: 100000 }
    - { key: net.core.netdev_max_backlog, value: 100000 }
    - { key: net.core.somaxconn, value: 65534 }
    - { key: net.ipv4.tcp_rmem, value: "4096 16060 64060" }
    - { key: net.ipv4.tcp_wmem, value: "4096 16384 262144" }
    - { key: net.netfilter.nf_conntrack_max, value: 131072 }
...
